<?php

namespace App\Http\Controllers\Web\Member;

use App\Http\Controllers\Web\_Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends _Controller
{
    public $module = [ 'member', 'user' ];
    public $iGroupType = 999;
    public $iAcType = [ 999, 901 ];

    public function __init_field ()
    {
        parent::__init_field(); // TODO: Change the autogenerated stub
        $this->field = [
            'get' => [
                [ 'title' => 'ID', 'name' => 'id', 'data' => 'users.id', ],
                [ 'title' => '帳號', 'name' => 'name', 'data' => 'users.name' ],
                [ 'title' => '帳號信箱', 'name' => 'email', 'data' => 'users.email' ],
                [ 'title' => '使用者性別', 'name' => 'info.gender', 'data' => 'users_info.gender', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
                [ 'title' => '使用者連絡電話', 'name' => 'info.contact', 'data' => 'users_info.contact', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
                [ 'title' => '使用者郵遞區號', 'name' => 'info.zip_code', 'data' => 'users_info.zip_code', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
                [ 'title' => '使用者城市', 'name' => 'info.city', 'data' => 'users_info.city', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
                [ 'title' => '使用者地區', 'name' => 'info.area', 'data' => 'users_info.area', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
                [ 'title' => '使用者地址', 'name' => 'info.address', 'data' => 'users_info.address', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
                [ 'title' => '使用者Line', 'name' => 'info.line_id', 'data' => 'users_info.line_id', 'table' => 'users_info', 'localKey' => 'id', 'foreignKey' => 'user_id' ],
            ]
        ];
    }

    /*
     *
     */
    public function index ()
    {
        return View()->make( 'web.member.user' )->with( [ 'module' => $this->module ] );
    }

    public function getList ( Request $request )
    {
        // condition
        $map = [];
        // new query
        $query = User::query()->with( [ 'info' ] )->where( $map );
        //
        $query = $this->__init_datatable_query( $query );
        //
        $total_count = $query->count();
        // Execute the query
        $data_arr = $query->skip( $request->input( 'iDisplayStart' ) )->take( $request->input( 'iDisplayLength' ) )->get();
        // Mapping the data
        foreach ($data_arr as $key => $var) {
            $var->DT_RowId = $var->id;
        }

        $this->rtndata ['status'] = 1;
        $this->rtndata ['sEcho'] = $request->input( 'sEcho' );
        $this->rtndata ['iTotalDisplayRecords'] = $total_count;
        $this->rtndata ['iTotalRecords'] = $total_count;
        $this->rtndata ['aaData'] = $data_arr;

        return response()->json( $this->rtndata );
    }
}
